import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

// Content-address every game dependency, including images referenced by CSS/Canvas.
// Run this after changing game files. Production builds reject forgotten stamps.
const root = fileURLToPath(new URL('../../public/rift-forge/', import.meta.url));
const check = process.argv.includes('--check');
const pending = new Map();
const read = path => pending.get(path) ?? readFileSync(resolve(root, path));
const hash = path => createHash('sha256').update(read(path)).digest('hex').slice(0, 12);
const url = path => `./${path}?v=${hash(path)}`;
const sprites = Object.fromEntries(['hero', 'guard', 'runner', 'seer', 'boss', 'maw', 'oracle'].map(name => [name, url(`assets/sprites/${name}.webp`)]));
pending.set('src/release.js', `// Generated by scripts/rift-forge/stamp-release.mjs\nwindow.RIFT_RELEASE = ${JSON.stringify({ version: '0.6.0', sprites, floor: url('assets/foundry-floor-v05.webp') }, null, 2)};\n`);
pending.set('src/style.css', String(read('src/style.css')).replace(/\.\.\/assets\/([\w/-]+\.webp)(?:\?v=[\w-]+)?/g, (_, path) => `../assets/${path}?v=${hash(`assets/${path}`)}`));
pending.set('index.html', String(read('index.html')).replace(/(src|href)="\.\/(src\/[\w-]+\.(?:js|css)|assets\/[\w/-]+\.webp)(?:\?v=[\w-]+)?"/g, (_, attr, path) => `${attr}="${url(path)}"`));
let stale = false;
for (const [path, content] of pending) {
 let previous = ''; try { previous = readFileSync(resolve(root, path), 'utf8'); } catch {}
 if (previous === content) continue;
 if (check) { console.error(`Unstamped Rift Forge asset: ${path}. Run node scripts/rift-forge/stamp-release.mjs`); stale = true; }
 else writeFileSync(resolve(root, path), content);
}
if (stale) process.exit(1);
console.log(check ? 'Rift Forge asset hashes verified.' : 'Rift Forge asset URLs stamped.');
